# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-10-14 19:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ikt_schedule', '0003_auto_20181014_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='subject',
            field=models.IntegerField(choices=[('sasasa', 'ssss'), ('wwww', 'ww')], default=None),
        ),
    ]
